let num=10;
console.log(num);
console.log(typeof(num));
num=false;
console.log(num);
console.log(typeof(num));
num= undefined;
console.log(num);
console.log(typeof(num));
num="Krishna";
console.log(num);
console.log(typeof(num));
